---
name: Tests html

on: [push]

jobs:
  test:
    name: Test html consistency

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: npm install
      - run: npm test
